### ISSUE TITLE
Missing alerts.zip file when building docker 

### ISSUE THREAD

**Issue by nanglo123** [gyorilab/outbreak_kg#10]
It seems like these lines here in the Dockerfile: https://github.com/gyorilab/outbreak_kg/blob/71216ae800363d930c04b75cc913de48003e7c50/kg/Dockerfile#L73-L76
reference a missing file: `alerts.zip`, that causes an unsucessful build of the docker image.

**Comment by bgyori** [comment]
This on purpose not added to version control
